title: çŒ«çƒåšå®¢
nav_color: 666
nav_img: blog.jpg
nav_qbt_left: 35%
description: è¿™é‡Œæ˜¯æçŒ«çƒçš„ä¸ªäººåšå®¢ï¼Œè®°å½•ç€çŒ«çƒå’ŒäºŒæ‰¯çš„æ—¥å¸¸ã€ä½œå“ã€ç¬”è®°ã€å°å·¥å…·ã€‚
keywords: çŒ«çƒ,æçŒ«çƒ,çŒ«çƒç¤¾é•¿,çŒ«çƒå’ŒäºŒæ‰¯,pvoå é¢†ä¸–ç•Œ
favicon: favicon.ico
nav_drop: <a href="/wangzhi">ğŸ”ç½‘å€æ”¶è—</a><a href="/liuyan" target="_blank">ç•™è¨€æ¿</a><a href="/notice">å¸¸è§é—®é¢˜</a><div class="nav_drop2"><a class="nav_drop_btn2">å…³äº &lt;</a><div class="nav_drop_down2"><a href="/maoqiu">ğŸ©å…³äº</a><a href="/chengjiu">ğŸ†è·å¾—æˆå°±</a><a href="/links">ğŸ»å‹æƒ…é“¾æ¥</a><a href="/myid">ğŸ­æˆ‘çš„è´¦å·</a><a href="/donate">ğŸ’°æ‰“èµ</a><a href="/private">ğŸ”’ç§äººç½‘é¡µ</a></div></div><div class="nav_drop2"><a class="nav_drop_btn2">æ¯”æ›´å¤šè¿˜å¤š &lt;</a><div class="nav_drop_down2"><a href="/richang">ğŸ‰çŒ«çƒå’ŒäºŒæ‰¯çš„æ—¥å¸¸</a><a href="/xiaojuchang">ğŸ¬çŒ«çƒå°å‰§åœº</a><a href="/wanyouxi">ğŸ®çŒ«çƒç©æ¸¸æˆ</a><a href="/riji">ğŸ“˜çŒ«çƒæ—¥è®°</a><a href="/pvoink">ğŸŒpvoå é¢†ä¸–ç•Œ</a><a href="/zatan">ğŸ’¡æ‚è°ˆ</a><a href="/xiaogongju">ğŸ“å°å·¥å…·</a></div></div>
mq: https://limaoqiu.com
mq_d: https://pvo.gitee.io
mq_i: /i
jquery: https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js

plugins:
  - jekyll-redirect-from

mq_url: https://æçŒ«çƒ.com